# Generated by Django 4.0.6 on 2022-08-04 14:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('sql_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('node_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('icon', models.PositiveIntegerField(choices=[(1, 'laptop'), (2, 'chip'), (3, 'kellis'), (4, 'tablet'), (5, 'ePhone'), (6, 'ePhone2'), (7, 'Psylance'), (8, 'PacificAir'), (9, 'Alchemist'), (10, 'DLCLaptop'), (11, 'DLCPC1'), (12, 'DLCPC2'), (13, 'DLCServer')], default=1)),
                ('node_type', models.PositiveIntegerField(choices=[(1, 'Computer'), (2, 'eosDevice')])),
            ],
        ),
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('sql_id', models.OneToOneField(limit_choices_to={'node_type': 1}, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='nodebuilder.node')),
                ('ip', models.CharField(max_length=255)),
                ('security', models.PositiveIntegerField(default=0)),
                ('comp_type', models.IntegerField(choices=[(1, 'Corporate'), (2, 'Home'), (3, 'Server'), (4, 'Empty')], default=4)),
                ('ports', models.JSONField(null=True)),
                ('portsForCrack', models.PositiveIntegerField(default=0)),
                ('proxyLevel', models.IntegerField(default=-1)),
                ('firewallLevel', models.IntegerField(default=-1)),
                ('firewallSolution', models.CharField(max_length=255)),
                ('firewallAdditionalTime', models.FloatField()),
                ('traceTime', models.IntegerField(default=-1)),
                ('adminType', models.PositiveIntegerField(choices=[(0, 'None'), (1, 'Basic'), (2, 'Progress'), (3, 'Fast')], default=0)),
                ('adminResetPassword', models.BooleanField(default=False)),
                ('adminIsSuper', models.BooleanField(default=False)),
                ('tracker', models.BooleanField(default=False)),
            ],
        ),
    ]
