# Generated by Django 4.0.6 on 2022-08-04 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodebuilder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='firewallAdditionalTime',
            field=models.FloatField(default='0.0'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='ip',
            field=models.CharField(default='1.2.3.4', max_length=255),
        ),
    ]
