# Generated by Django 4.0.6 on 2022-08-04 18:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('nodebuilder', '0002_alter_computer_firewalladditionaltime_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameObject',
            fields=[
                ('sql_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_type', models.PositiveIntegerField(choices=[(1, 'Node'), (2, 'File'), (3, 'Connection'), (4, 'Daemon')], default=1)),
            ],
        ),
        migrations.AlterField(
            model_name='node',
            name='sql_id',
            field=models.OneToOneField(limit_choices_to={'object_type': 1}, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='nodebuilder.gameobject'),
        ),
    ]
