# Generated by Django 4.0.6 on 2022-08-07 17:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('nodebuilder', '0003_gameobject_alter_node_sql_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='sql_id',
        ),
        migrations.AddField(
            model_name='computer',
            name='icon',
            field=models.PositiveIntegerField(choices=[(1, 'Laptop'), (2, 'Chip'), (3, 'Kellis'), (4, 'Tablet'), (5, 'ePhone'), (6, 'ePhone2'), (7, 'Psylance'), (8, 'PacificAir'), (9, 'Alchemist'), (10, 'DLCLaptop'), (11, 'DLCPC1'), (12, 'DLCPC2'), (13, 'DLCServer')], default=1),
        ),
        migrations.AddField(
            model_name='computer',
            name='name',
            field=models.CharField(default='FILL THIS IN', max_length=255),
        ),
        migrations.AddField(
            model_name='computer',
            name='node_id',
            field=models.CharField(default='TBD', max_length=255),
        ),
        migrations.AddField(
            model_name='computer',
            name='node_type',
            field=models.PositiveIntegerField(choices=[(1, 'Computer'), (2, 'eosDevice')], default=None),
        ),
        migrations.AddField(
            model_name='computer',
            name='object_type',
            field=models.PositiveIntegerField(choices=[(1, 'Node'), (2, 'File'), (3, 'Connection'), (4, 'Daemon')], default=1),
        ),
        migrations.AlterField(
            model_name='computer',
            name='sql_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='GameObject',
        ),
        migrations.DeleteModel(
            name='Node',
        ),
    ]
