# Generated by Django 4.0.6 on 2022-08-11 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodebuilder', '0005_alter_computer_name_alter_computer_node_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='firewallAdditionalTime',
            field=models.FloatField(blank=True, default='0.0'),
        ),
        migrations.AlterField(
            model_name='computer',
            name='firewallSolution',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='computer',
            name='object_type',
            field=models.PositiveIntegerField(choices=[(1, 'Node'), (2, 'File'), (3, 'Connection'), (4, 'Daemon')], default=None),
        ),
    ]
