# Generated by Django 4.0.6 on 2022-08-11 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodebuilder', '0008_alter_computer_name_alter_computer_node_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='adminIsSuper',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='computer',
            name='adminResetPassword',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='computer',
            name='tracker',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
