# Generated by Django 4.0.6 on 2022-08-12 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodebuilder', '0010_alter_computer_ports'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='obj_children',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
